"""Episode-grounded interpretability helpers for VLA robot datasets.

The public API centers on LeRobot v3 dataset roots with an optional
``vla_lens/`` interpretability overlay. ``TraceDataset`` opens those roots,
nested batch outputs, and exposes one query surface for selectors, probes,
artifacts, and dashboard state. PI0.5-specific capture helpers remain isolated
under ``vla_lens.pi05``.
"""

from __future__ import annotations

from vla_lens.action_generation import SavedActionGeneration, save_action_generation_artifact
from vla_lens.artifacts import LensArtifact
from vla_lens.capture import (
    COMMON_ROBOTICS_DATASETS,
    COMMON_ROBOTICS_ENVIRONMENTS,
    LEROBOT_ACTION,
    LEROBOT_OBSERVATION_STATE,
    LEROBOT_V3_VERSION,
    VLA_LENS_OVERLAY_DIR,
    ActionGeneratorSpec,
    CaptureSite,
    CaptureSpec,
    ContractIssue,
    DatasetDescriptor,
    DatasetEpisodeAdapter,
    EnvironmentAdapter,
    EnvironmentDescriptor,
    EnvironmentSupport,
    EpisodeRecord,
    LeRobotV3ValidationResult,
    ModelCaptureAdapter,
    ModelDescriptor,
    ModelTraceRecord,
    PolicyCallRecord,
    RoboticsDatasetSupport,
    TraceRecord,
    TransformerSegmentSpec,
    merge_episode_and_model_trace,
    validate_lerobot_v3_dataset,
    vla_lens_overlay_path,
)
from vla_lens.dataset import write_lerobot_trace_record
from vla_lens.pi05.interaction_metrics import (
    InteractionMetricsArtifact,
    save_pi05_interaction_metrics_artifact,
)
from vla_lens.selectors import ActivationQuery, FeatureMatrix, FeatureView
from vla_lens.synthetic import create_synthetic_trace_dataset
from vla_lens.target_object import (
    SavedTargetObjectEncoding,
    save_target_object_encoding_artifact,
)
from vla_lens.traces import ActivationSpec, ArraySpec, TraceBundle, TraceDataset, TraceManifest
from vla_lens.validation import (
    CAPTURE_PROFILE_REQUIREMENTS,
    FULL_REQUIRED_MODEL_SITE_ROLES,
    DatasetValidationResult,
    TraceValidationResult,
    manifest_hash,
    validate_trace_bundle,
    validate_trace_dataset,
)
from vla_lens.workbench import (
    AnalysisRunSpec,
    AxisSpec,
    CohortSpec,
    GraphEdgeSpec,
    GraphNodeRef,
    ImageFrameSpec,
    InterventionRunSpec,
    LensArraySpec,
    MediaSpec,
    ModelSiteSpec,
    OverlayScoreSpec,
    PanelRecipe,
    PanelRegistryEntry,
    SavedWorkspace,
    SelectionState,
    StorageRef,
    TableSpec,
    UnitRef,
    axis_registry,
    cohort_from_selection,
    compare_cohorts,
    graph_edge_types,
    graph_from_selection,
    image_frame_catalog,
    lens_array_catalog,
    lens_array_meta,
    list_analysis_runs,
    list_cohorts,
    list_intervention_runs,
    list_workspaces,
    media_catalog,
    model_site_catalog,
    normalize_axis_values,
    normalize_selection,
    panel_registry,
    projection_points,
    query_table,
    resolve_selection,
    resolve_workspace,
    save_analysis_run,
    save_cohort,
    save_intervention_run,
    save_workspace,
    slice_lens_array,
    spatial_overlay_contracts,
    table_catalog,
    unit_profile,
    validate_workbench_contracts,
    workbench_manifest,
)

__all__ = [
    "ActivationQuery",
    "ActivationSpec",
    "CAPTURE_PROFILE_REQUIREMENTS",
    "COMMON_ROBOTICS_DATASETS",
    "COMMON_ROBOTICS_ENVIRONMENTS",
    "ActionGeneratorSpec",
    "CaptureSite",
    "CaptureSpec",
    "AnalysisRunSpec",
    "ArraySpec",
    "AxisSpec",
    "CohortSpec",
    "ContractIssue",
    "DatasetDescriptor",
    "DatasetEpisodeAdapter",
    "DatasetValidationResult",
    "EpisodeRecord",
    "EnvironmentAdapter",
    "EnvironmentDescriptor",
    "EnvironmentSupport",
    "FeatureMatrix",
    "FeatureView",
    "FULL_REQUIRED_MODEL_SITE_ROLES",
    "GraphEdgeSpec",
    "GraphNodeRef",
    "ImageFrameSpec",
    "InterventionRunSpec",
    "InteractionMetricsArtifact",
    "LensArraySpec",
    "LensArtifact",
    "MediaSpec",
    "ModelCaptureAdapter",
    "ModelDescriptor",
    "ModelSiteSpec",
    "ModelTraceRecord",
    "OverlayScoreSpec",
    "PanelRegistryEntry",
    "PanelRecipe",
    "PolicyCallRecord",
    "RoboticsDatasetSupport",
    "LeRobotV3ValidationResult",
    "LEROBOT_ACTION",
    "LEROBOT_OBSERVATION_STATE",
    "LEROBOT_V3_VERSION",
    "VLA_LENS_OVERLAY_DIR",
    "TransformerSegmentSpec",
    "SavedActionGeneration",
    "SavedTargetObjectEncoding",
    "SavedWorkspace",
    "SelectionState",
    "StorageRef",
    "TableSpec",
    "TraceBundle",
    "TraceDataset",
    "TraceManifest",
    "TraceRecord",
    "TraceValidationResult",
    "UnitRef",
    "axis_registry",
    "cohort_from_selection",
    "compare_cohorts",
    "create_synthetic_trace_dataset",
    "graph_edge_types",
    "graph_from_selection",
    "image_frame_catalog",
    "lens_array_catalog",
    "lens_array_meta",
    "list_cohorts",
    "list_analysis_runs",
    "list_intervention_runs",
    "list_workspaces",
    "media_catalog",
    "manifest_hash",
    "merge_episode_and_model_trace",
    "model_site_catalog",
    "normalize_axis_values",
    "normalize_selection",
    "panel_registry",
    "projection_points",
    "query_table",
    "resolve_workspace",
    "resolve_selection",
    "save_cohort",
    "save_analysis_run",
    "save_intervention_run",
    "save_pi05_interaction_metrics_artifact",
    "save_workspace",
    "slice_lens_array",
    "spatial_overlay_contracts",
    "table_catalog",
    "unit_profile",
    "validate_workbench_contracts",
    "validate_trace_bundle",
    "validate_trace_dataset",
    "validate_lerobot_v3_dataset",
    "vla_lens_overlay_path",
    "save_action_generation_artifact",
    "save_target_object_encoding_artifact",
    "workbench_manifest",
    "write_lerobot_trace_record",
]
