"""Runtime-free intervention evidence contracts."""

from vla_lens.interventions.action_basis import (
    ActionBasisResolution,
    ActionBasisResult,
    ActionNormalizationSpec,
    ActionSchemaRef,
    action_delta_metrics,
    resolve_action_basis,
)
from vla_lens.interventions.artifacts import (
    intervention_run_to_lens_artifact,
    intervention_sweep_to_lens_artifact,
)
from vla_lens.interventions.counterfactuals import (
    ActionArrayRef,
    CounterfactualMetrics,
    CounterfactualPairManifest,
    CounterfactualRecipe,
    EvaluationDecision,
    PatchDecisionThresholds,
    PatchStudyArtifact,
    PatchStudySpec,
    PatchTrialManifest,
    counterfactual_action_metrics,
    evaluate_patch_trial,
)
from vla_lens.interventions.families import (
    ArtifactFamilyContract,
    artifact_family_for_type,
    artifact_family_registry,
    legal_operators_for_artifact,
    legal_outcomes_for_artifact,
    required_controls_for_artifact_claim,
    target_from_discovery_artifact,
)
from vla_lens.interventions.patch_study import (
    PlannedPatchTrial,
    build_patch_trial_request,
    expand_patch_study,
    patch_study_request_sha256,
)
from vla_lens.interventions.patch_study_store import PatchStudyProgress, PatchStudyStore
from vla_lens.interventions.preflight import intervention_preflight
from vla_lens.interventions.results import (
    ActionOutcomeResult,
    AggregateOutcomeResult,
    CohortInterventionRequest,
    ControlResult,
    InterventionRun,
    InterventionStudy,
    InterventionSweep,
    InterventionTrial,
    RolloutOutcomeResult,
    SweepAxis,
    TokenOutcomeResult,
)
from vla_lens.interventions.runtime import ActionInterventionExecutor, RuntimeTrialOutput
from vla_lens.interventions.specs import (
    ActionBasisRequest,
    ContextSpec,
    ControlSpec,
    DonorSpec,
    InterventionOperatorSpec,
    InterventionScheduleSpec,
    OutcomeSpec,
    PolicyCallRef,
    PreflightCheck,
    RecipientSpec,
    RuntimePreflightResult,
    RuntimeResolution,
    TargetSpec,
    TraceRef,
)
from vla_lens.interventions.sweeps import (
    aggregate_outcome_metric,
    build_intervention_study,
    build_intervention_sweep,
    promote_run_to_sweep,
)

__all__ = [
    "ActionArrayRef",
    "ActionBasisRequest",
    "ActionBasisResolution",
    "ActionBasisResult",
    "ActionInterventionExecutor",
    "ActionNormalizationSpec",
    "ActionSchemaRef",
    "ArtifactFamilyContract",
    "AggregateOutcomeResult",
    "ActionOutcomeResult",
    "CohortInterventionRequest",
    "CounterfactualMetrics",
    "CounterfactualPairManifest",
    "CounterfactualRecipe",
    "ContextSpec",
    "ControlResult",
    "ControlSpec",
    "DonorSpec",
    "EvaluationDecision",
    "InterventionOperatorSpec",
    "InterventionRun",
    "InterventionScheduleSpec",
    "InterventionStudy",
    "InterventionSweep",
    "InterventionTrial",
    "OutcomeSpec",
    "PatchDecisionThresholds",
    "PatchStudyArtifact",
    "PatchStudySpec",
    "PatchStudyProgress",
    "PatchStudyStore",
    "PatchTrialManifest",
    "PlannedPatchTrial",
    "PolicyCallRef",
    "PreflightCheck",
    "RecipientSpec",
    "RolloutOutcomeResult",
    "RuntimePreflightResult",
    "RuntimeResolution",
    "RuntimeTrialOutput",
    "SweepAxis",
    "TargetSpec",
    "TokenOutcomeResult",
    "TraceRef",
    "action_delta_metrics",
    "aggregate_outcome_metric",
    "artifact_family_for_type",
    "artifact_family_registry",
    "build_intervention_study",
    "build_intervention_sweep",
    "build_patch_trial_request",
    "counterfactual_action_metrics",
    "evaluate_patch_trial",
    "expand_patch_study",
    "intervention_preflight",
    "intervention_run_to_lens_artifact",
    "intervention_sweep_to_lens_artifact",
    "legal_operators_for_artifact",
    "legal_outcomes_for_artifact",
    "promote_run_to_sweep",
    "patch_study_request_sha256",
    "required_controls_for_artifact_claim",
    "resolve_action_basis",
    "target_from_discovery_artifact",
]
